### ISSUE TITLE
Install and configure Jenkins

### ISSUE THREAD

**Issue by Protopuch** [Protopuch/raccoon-configuration#1]
We need to run and configure Jenkins instance in digitalocean.

**Comment by Protopuch** [comment]
Поставили на удаленный сервер docher, развернули jenkens. Настроили автоматические сборки на основании gradle настроек. Отвалились при сборке из за перегруженности нехватки памяти.
Необходимо: 
1. Развернуть на рабочей станции jenkins, настроить сборку на основании gradle настроек.

**Comment by Protopuch** [comment]
Поставили на второй сервер(167.99.36.126) docker, развернули там jenkens. Создали сборку которая подтягивает изменение в проекте raccoon-backend. Столкнулись с проблемой нехватки памяти при запуске сборки. Требуется.
Посмотреть системный журнал, возможно на сервере запрещено использование SWP памяти (жесткого диска) либо выделить больше памяти. 
Стопнули на первом сервере(206.189.99.157) docker контейнер с jenkens.

**Comment by Protopuch** [comment]
Jenkins
Login: raccoon

**Comment by ilmat192** [comment]
Добавили памяти на виртуалке. Успешно запустили тесты бэкенда.
Искали путь для отображения статус билда на GitHub. Пока не нашли.

**Comment by ilmat192** [comment]
Jenkins обновлен, коммит-статусы работают.
